language: java

sudo: false

before_script:
  - wget 'wget https://releases.hashicorp.com/consul/0.9.2/consul_0.9.2_linux_amd64.zip?_ga=2.171315744.1078551265.1504110649-551520754.1504110649'
  - mv "consul_0.9.2_linux_amd64.zip?_ga=2.171315744.1078551265.1504110649-551520754.1504110649 consul_0.9.2_linux_amd64.zip"
  - unzip "consul_0.9.2_linux_amd64.zip"
  - ./consul --version
  - ./consul agent -dev
  - sleep 5
  
jdk:
  - oraclejdk8
  
install:
  - cd config-web/ && mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
